"""empty message

Revision ID: 749cc6a0958a
Revises: dcff8b3281f1
Create Date: 2020-04-29 22:33:37.860825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749cc6a0958a'
down_revision = 'dcff8b3281f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
